"""add User.avatar_hash

Revision ID: d6f4efe3ffe1
Revises: 431d275d6a70
Create Date: 2015-12-23 12:39:35.906573

"""

# revision identifiers, used by Alembic.
revision = 'd6f4efe3ffe1'
down_revision = '431d275d6a70'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
